Add Brave path for Windows
gopasspw/gopass-jsonapi pull request #13
Opened 2021-02-17 20:59 UTC by lobre

Hello,

I recently switched browsers from Chrome to Brave and I happily discovered glad that the setup of `jsonapi` was already existing for Linux!

However, when I switched as well on my Windows machine, I was surprised that Brave was not out of the box supported.

I don’t know if there is a reason for not having the same Browser support between Linux / Mac / Windows but I propose to add Brave to the Windows build with that PR.

Tested on my Windows 10 machine.

Have a nice day,
Loric

2021-02-17 21:12 UTC, lobre commented
By the way, I cannot figure out how the commit message should be written (I cannot find the exact rule when I check the CommitCheck details in the build).

If you agree to move forward with that PR, can you please guide me on that point?

Thanks a lot.

2021-03-03 11:24 UTC, Pharb commented
Hi @lobre, thanks a lot for the contribution!

> I don’t know if there is a reason for not having the same Browser support between Linux / Mac / Windows but I propose to add Brave to the Windows build with that PR.

It mainly depends on community contributions. I don't know other contributors who use Brave on Windows.

> By the way, I cannot figure out how the commit message should be written (I cannot find the exact rule when I check the CommitCheck details in the build).

Sorry for the confusing rules around commit messages, please see the documentation here: https://github.com/gopasspw/gopass/blob/master/CONTRIBUTING.md#pull-request-checklist

2021-03-03 11:25 UTC, Pharb requested changes
> Tested on my Windows 10 machine.

That's great :D Thanks for testing it!

2021-03-03 11:25 UTC, Pharb commented on internal/jsonapi/manifest/setup_windows.go
> +		"brave":    `Software\BraveSoftware\Brave-Browser\NativeMessagingHosts\` + Name,
Would be nice if you could also add Brave to supported browsers in README.md

2021-03-03 13:16 UTC, lobre commented
Hi @Pharb,

I have updated the README.md to include Brave in the list of supported browsers for Windows.

I have also amended by commit to update the commit message and respect the format.

Let me know if there is anything else

2021-03-03 22:43 UTC, Pharb approved these changes
Nice, thanks a lot!

2021-03-03 22:43 UTC, merged